Patch libpgf to support Emscripten
Compilation with Emscripten was failing because some types aliases are
conditionally defined in PGFPlatform.h, and there is no default.

The error was:

$ emmake make
make: make
make  all-recursive
make[1]: Entering directory '/src'
Making all in src
make[2]: Entering directory '/src/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile /emsdk/upstream/emscripten/em++ -DHAVE_CONFIG_H -I. -I..  -I../include    -g -O2 -MT Decoder.lo -MD -MP -MF .deps/Decoder.Tpo -c -o Decoder.lo Decoder.cpp
libtool: compile:  /emsdk/upstream/emscripten/em++ -DHAVE_CONFIG_H -I. -I.. -I../include -g -O2 -MT Decoder.lo -MD -MP -MF .deps/Decoder.Tpo -c Decoder.cpp  -fPIC -DPIC -o .libs/Decoder.o
In file included from Decoder.cpp:29:
In file included from ./Decoder.h:32:
In file included from ../include/PGFstream.h:32:
../include/PGFtypes.h:115:2: error: unknown type name 'UINT8'
        UINT8 version;                          ///< PGF version
        ^
../include/PGFtypes.h:124:2: error: unknown type name 'UINT32'
        UINT32 hSize;                           ///< total size of PGFHeader, [ColorTable], and [UserData] in bytes (since Version 6: 4 Bytes)
        ^
../include/PGFtypes.h:133:19: error: unknown type name 'UINT8'
        PGFVersionNumber(UINT8 _major, UINT8 _year, UINT8 _week) : major(_major), year(_year), week(_week) {}
                         ^
../include/PGFtypes.h:133:33: error: unknown type name 'UINT8'
        PGFVersionNumber(UINT8 _major, UINT8 _year, UINT8 _week) : major(_major), year(_year), week(_week) {}
                                       ^
../include/PGFtypes.h:133:46: error: unknown type name 'UINT8'
        PGFVersionNumber(UINT8 _major, UINT8 _year, UINT8 _week) : major(_major), year(_year), week(_week) {}
                                                    ^
../include/PGFtypes.h:140:2: error: unknown type name 'UINT16'
        UINT16 major : 4;       ///< major version number
        ^
../include/PGFtypes.h:141:2: error: unknown type name 'UINT16'
        UINT16 year  : 6;       ///< year since 2000 (year 2001 = 1)
        ^
../include/PGFtypes.h:142:2: error: unknown type name 'UINT16'
        UINT16 week  : 6;       ///< week number in a year
        ^
../include/PGFtypes.h:152:2: error: unknown type name 'UINT32'
        UINT32 width;                           ///< image width in pixels
        ^
../include/PGFtypes.h:153:2: error: unknown type name 'UINT32'
        UINT32 height;                          ///< image height in pixels
        ^
../include/PGFtypes.h:154:2: error: unknown type name 'UINT8'
        UINT8 nLevels;                          ///< number of FWT transforms
        ^
../include/PGFtypes.h:155:2: error: unknown type name 'UINT8'
        UINT8 quality;                          ///< quantization parameter: 0=lossless, 4=standard, 6=poor quality
        ^
../include/PGFtypes.h:156:2: error: unknown type name 'UINT8'
        UINT8 bpp;                                      ///< bits per pixel
        ^
../include/PGFtypes.h:157:2: error: unknown type name 'UINT8'
        UINT8 channels;                         ///< number of channels
        ^
../include/PGFtypes.h:158:2: error: unknown type name 'UINT8'
        UINT8 mode;                                     ///< image mode according to Adobe's image modes
        ^
../include/PGFtypes.h:159:2: error: unknown type name 'UINT8'
        UINT8 usedBitsPerChannel;       ///< number of used bits per channel in 16- and 32-bit per channel modes
        ^
../include/PGFtypes.h:169:2: error: unknown type name 'RGBQUAD'
        RGBQUAD clut[ColorTableLen];///< color table for indexed color images (optional part of file header)
        ^
../include/PGFtypes.h:170:2: error: unknown type name 'UINT8'
        UINT8 *userData;                        ///< user data of size userDataLen (optional part of file header)
        ^
../include/PGFtypes.h:171:2: error: unknown type name 'UINT32'
        UINT32 userDataLen;                     ///< user data size in bytes (not part of file header)
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
em++: error: '/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=8 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DHAVE_CONFIG_H -I. -I.. -I../include -g -O2 -MT Decoder.lo -MD -MP -MF .deps/Decoder.Tpo -c -fPIC -DPIC Decoder.cpp -o .libs/Decoder.o' failed (returned 1)
make[2]: *** [Makefile:451: Decoder.lo] Error 1
make[2]: Leaving directory '/src/src'
make[1]: *** [Makefile:420: all-recursive] Error 1
make[1]: Leaving directory '/src'
make: *** [Makefile:348: all] Error 2
emmake: error: 'make' failed (returned 2)